---
# tasks file for role_bi_sysctl
- name: Gather machine type specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "baseinstall_type_{{ baseinstall_type }}.yml"

- name: Include os independent variables.
  include_vars: "vars/main.yml"

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
  tags: [ never, debug ]

- name: Configure role_bi_sysctl
  include: 02-configure.yml

